"""Add name for task

Revision ID: ed247e791636
Revises: 81caeafbe0ac
Create Date: 2023-03-01 00:48:46.059443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed247e791636'
down_revision = '81caeafbe0ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'name')
    # ### end Alembic commands ###
